[tpm2.0] Support sha1 fallback, layered sealing
  If sha256 bank is not present for some reason on tpm2 hardware,
  support the sha1 protocol as a fallback (sealing/unsealing/extend/policy).
  Additionally, implement layered sealing to support case where firmware
  measurements fail to use more secure hash algorithms.  Layered sealing
  encrypts the config key against multiple PCR banks in the event of the
  above case.

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

diff --git a/recipes-openxt/openxt/openxt-keymanagement/key-functions b/recipes-openxt/openxt/openxt-keymanagement/key-functions
--- a/recipes-openxt/openxt/openxt-keymanagement/key-functions
+++ b/recipes-openxt/openxt/openxt-keymanagement/key-functions
@@ -22,6 +22,19 @@ is_tpm_2_0 () {
    [ -e /sys/class/tpm/tpm0/device/description ] && cat /sys/class/tpm/tpm0/device/description | grep "2.0" &>/dev/null
 }
 
+pcr_bank_exists () {
+    local alg_in=$1
+
+    banks=$(tpm2_listpcrs -s | cut -d ':' -f 2)
+    for bank in $banks; do
+        alg=$(echo $bank | cut -d '(' -f 1)
+        if [ "$alg" = $alg_in ]; then
+            return 0
+        fi
+    done
+    return 1
+}
+
 # LUKS Key Slots 
 RSLOT=0
 ESLOT=1
@@ -532,6 +545,11 @@ platform_unlock() {
     return $?
 }
 
+#For TPM 2.0, we perform 'layered' unsealing. In the opposite order of the seal, we attempt
+#to unseal the encrypted blob for each hash alg in the set of supported algs of the tpm. The output
+#is always tried against cryptsetup in event that the sealed blob is the only layer.
+#(ie. TPM supports ONLY sha256, and doesn't expose sha1 or other hash algs). The code could be simplified
+#if the unsealed output is redirected to a file, but we never want to risk storing the decrypted key on disk.
 encrypted_unlock() {
     local part="${1}"
     local name="${2}"
@@ -541,8 +559,23 @@ encrypted_unlock() {
     local tpm2=$?
     if [ "${tpm2}" -eq 0 ]; 
     then
-        tpm2_unsealdata -H 0x81000000 -n "${key_file}" -u "${key_file}.pub" -g 0xB -r 0 -r 1 -r 2 -r 3 -r 15 -r 17 -r 18 -r 19 2>/dev/null | cryptsetup -q -d - -S ${ESLOT} luksOpen "${part}" "${name}" >/dev/null 2>&1
-        ret=$?
+        local unseal_file=${key_file}
+        #try unsealing, if failed, its possibly a rolled up blob, try the next alg in the series
+        if pcr_bank_exists "TPM_ALG_SHA256"; then
+            tpm2_unsealdata -H 0x81000000 -n "${unseal_file}" -u "${key_file}.pub.sha256" -g 0xB -r 0 -r 1 -r 2 -r 3 -r 15 -r 17 -r 18 -r 19 | cryptsetup -q -d - -S ${ESLOT} luksOpen "${part}" "${name}" >/dev/null 2>&1
+            ret=$?
+            if [ $ret -eq 0 ]; then
+                return $ret
+            else
+                 tpm2_unsealdata -H 0x81000000 -n "${unseal_file}" -u "${key_file}.pub.sha256" -g 0xB -r 0 -r 1 -r 2 -r 3 -r 15 -r 17 -r 18 -r 19 > "${key_file}.tmp"
+                unseal_file="${key_file}.tmp"
+            fi
+        fi
+        if pcr_bank_exists "TPM_ALG_SHA1"; then
+            tpm2_unsealdata -H 0x81000001 -n "${unseal_file}" -u "${key_file}.pub.sha1" -g 0x4 -r 0 -r 1 -r 2 -r 3 -r 15 -r 17 -r 18 -r 19 | cryptsetup -q -d - -S ${ESLOT} luksOpen "${part}" "${name}" >/dev/null 2>&1
+            ret=$?
+        fi
+        [ -e "${key_file}.tmp" ] && rm "${key_file}.tmp"
     else
         tpm_unsealdata_sa -z -i $key_file | \
             cryptsetup -q -d - -S ${ESLOT} luksOpen "${part}" "${name}" >/dev/null 2>&1
diff --git a/recipes-openxt/openxt/openxt-measuredlaunch/seal-system b/recipes-openxt/openxt/openxt-measuredlaunch/seal-system
--- a/recipes-openxt/openxt/openxt-measuredlaunch/seal-system
+++ b/recipes-openxt/openxt/openxt-measuredlaunch/seal-system
@@ -12,6 +12,11 @@
     exit 1
 }
 
+. /usr/lib/openxt/key-functions
+[ $? -eq 0 ] || {
+    echo "failed to load key-functions"
+    exit 1
+}
 
 err() {
     echo "seal-system: $1" >&2
@@ -67,16 +72,25 @@ case $operation in
 seal)
     if [ "${tpm2}" -eq 0 ];
     then
+        sealerr=0
+        seal_file=${config_key}
         clean_old_tpm_files
-        sealout=$(tpm2_sealdata -H 0x81000000 -I ${config_key} -O ${sealed_key} -o ${sealed_key}.pub -g 0xB -G 8 -A o -b 0x492 $(cat /config/config.pcrs) 2>&1)
-        sealerr=$?
+        if pcr_bank_exists "TPM_ALG_SHA1"; then
+            sealout=$(tpm2_sealdata -H 0x81000001 -I ${seal_file} -O ${sealed_key} -o ${sealed_key}.pub.sha1 -g 0x4 -G 8 -A o -b 0x492 $(cat /config/config.pcrs) 2>&1)
+            sealerr=$?
+            seal_file=${sealed_key}
+        fi
+        if pcr_bank_exists "TPM_ALG_SHA256" && [ ${sealerr} -eq 0 ]; then
+            sealout=$(tpm2_sealdata -H 0x81000000 -I ${seal_file} -O ${sealed_key} -o ${sealed_key}.pub.sha256 -g 0xB -G 8 -A o -b 0x492 $(cat /config/config.pcrs) 2>&1)
+            sealerr=$?
+        fi
     else
         sealout=$(tpm_sealdata_sa -i ${config_key} \
             -o ${sealed_key} -z $(cat ${pcr_list}) 2>&1)
         sealerr=$?
     fi
 
-    if [ $sealerr -eq 0 ]; then
+    if [ $sealerr -eq 0 ] && [ -e ${sealed_key} ]; then
         # store PCR hints for recovery
         if [ -d "${TPM_DEV}" ]; then
             [ -f "${bad_pcrs}" ] && rm "${bad_pcrs}"
diff --git a/recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions b/recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
--- a/recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
+++ b/recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
@@ -30,6 +30,18 @@ clean_old_tpm_files () {
     [ -e /boot/system/tpm/config.tss.pub ] && rm /boot/system/tpm/config.tss.pub
 }
 
+alg_to_handle () {
+    alg=$1
+    case $alg in
+        0x000b)
+            echo "0x81000000"
+            ;;
+        0x0004)
+            echo "0x81000001"
+            ;;
+    esac
+}
+
 tcsd_start() {
     is_tpm_2_0
     local tpm2=$?
@@ -223,6 +235,33 @@ tpm_has_ek() {
     return $ret
 }
 
+#Taking ownership for tpm2 is slightly more complicated. Encapsulate this process
+#in its own function, checking err after each critical operation.
+tpm2_ownership () {
+    passwd=$1
+
+    #Taking endoresement password AND lockout password to fully own tpm
+    err=$(tpm2_takeownership -o "${passwd}" -e "${passwd}" 2>&1)
+    ret=$?
+    [ ${ret} -ne 0 ] && echo ${err} && return ${ret}
+
+    banks=$(tpm2_listpcrs -s | cut -d ':' -f 2)
+    ret=$?
+    [ ${ret} -ne 0 ] && echo "Failed to list pcr banks" && return ${ret}
+    #Create our primary object
+    for bank in $banks; do
+        alg=$(echo $bank | cut -d '(' -f 2 | cut -d ')' -f 1)
+        handle=$(echo -n "${passwd}" | tpm2_createprimary -A o -g ${alg} -G 0x1 -P | grep Handle | cut -d ':' -f 2)
+        ret=$?
+        [ ${ret} -ne 0 ] && echo "Failed to create primary" && return ${ret}
+        #Make it permanent for this measured install
+        err=$(tpm2_evictcontrol -A o -H ${handle} -S $(alg_to_handle ${alg}) -P "${passwd}" 2>&1)
+        ret=$?
+        [ ${ret} -ne 0 ] && echo ${err} && return ${ret}
+    done
+    return 0
+}
+
 # Function to take ownership of the TPM.  Wraps some common functionality to
 #   create an EK and check that we can seal with the well-known SRK.
 # parameter 0: password
@@ -253,12 +292,7 @@ tpm_take_ownership() {
     
     if [ "${tpm2}" -eq 0 ]; 
     then
-        #Taking endoresement password AND lockout password to fully own tpm
-        err=$(tpm2_takeownership -o "${passwd}" -e "${passwd}" 2>&1)
-        #Create our primary object
-        handle=$(echo -n "${passwd}" | tpm2_createprimary -A o -g 0xB -G 0x1 -P | grep Handle | cut -d ':' -f 2) 
-        #Make it permanent for this measured install
-        err=$(tpm2_evictcontrol -A o -H ${handle} -S 0x81000000 -P "${passwd}" 2>&1)
+        err=$(tpm2_ownership ${passwd})
     else
         # take ownership of TPM
         err=$(cat "${passwd}" | tpm_takeownership --srk-well-known --stdin 2>&1)
@@ -322,9 +356,21 @@ tpm_forward_seal() {
 
     if [ "${tpm2}" -eq 0 ];
     then 
+        seal_file=${key}
         clean_old_tpm_files
-        tpm2_sealdata -H 0x81000000 -I ${key} -O ${tss} -o ${tss}.pub -g 0xB -G 8 -A o -b 0x492 ${pcrs} 2>&1
-        return $?
+        if pcr_bank_exists "TPM_ALG_SHA1"; then
+            tpm2_sealdata -H 0x81000001 -I ${seal_file} -O ${tss} -o ${tss}.pub.sha1 -g 0x4 -G 8 -A o -b 0x492 ${pcrs} 2>&1
+            err=$?
+            seal_file=${tss}
+            if [ $err -ne 0 ]; then return $err; fi
+        fi
+        if pcr_bank_exists "TPM_ALG_SHA256"; then
+            tpm2_sealdata -H 0x81000000 -I ${seal_file} -O ${tss} -o ${tss}.pub.sha256 -g 0xB -G 8 -A o -b 0x492 ${pcrs} 2>&1
+            err=$?
+            if [ $err -ne 0 ]; then return $err; fi
+        fi
+        [ -e ${tss} ] && return 0
+        return 1
     else
         /etc/init.d/trousers status > /dev/null 2>&1
         if [ $? -ne 0 ]; then
