[kirkstone] Use new override syntax
Since the Honister release, OE recipes now use a new syntax
for any variables that use a conditional override. This applies
to any variable that was once appended to by an underscore; they
are now appended to with a colon. A few examples below:

do_compile_append() --> do_compile:append()
RDEPENDS_${PN}      --> RDEPENDS:${PN}

These can also be chained together:

do_package_append_${PN}-dev --> do_package:append:${PN}-dev

This is much clearer as the colon will not conflict with any
characters that might already be present in the variable name.

These changes were largely made with the convenience script that
is provided here: <oe-core>/scripts/contrib/convert-overrides.py

Signed-off-by: Nicholas Tsirakis <tsirakisn@ainfosec.com>
Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

diff --git a/recipes-openxt/vhd-scripts/vhd-scripts/vhd-dm-remove b/recipes-openxt/vhd-scripts/vhd-scripts/vhd-dm-remove
--- a/recipes-openxt/vhd-scripts/vhd-scripts/vhd-dm-remove
+++ b/recipes-openxt/vhd-scripts/vhd-scripts/vhd-dm-remove
@@ -77,7 +77,7 @@ vhd_dm_partition_name()
     return 0
 }
 
-vhd_dm_remove_partitions()
+vhd_dm:remove_partitions()
 {
     local partition=1
     "$FDISK_BIN" -lu "$DEV" | grep -A5 Device | tail -n+2 | sed 's/\*/ /g' |
@@ -103,7 +103,7 @@ vhd_dm_holders()
     return 0
 }
 
-vhd_dm_remove()
+vhd_dm:remove()
 {
     local minors=""
     [ "$DEACTIVATE_TAPDISKS" = "true" ] && {
@@ -112,7 +112,7 @@ vhd_dm_remove()
     }
 
     [ "$REMOVE_PARTITIONS" = "yes" ] && {
-	vhd_dm_remove_partitions || die "error removing partitions"
+	vhd_dm:remove_partitions || die "error removing partitions"
     }
 
     "$DMSETUP_BIN" remove -f "$DEV" 2>/dev/null || \
@@ -174,4 +174,4 @@ fi
 
 [ -e "$DEV" ] || die "$NAME ($DEV) does not exist"
 
-vhd_dm_remove
+vhd_dm:remove
