[tpm2.0] Write tboot policy to both tpm nv indices
  Tboot either checks for policy at 0x01200001 or 0x01c10131
  depending on a property it reads in its acmod.c. We can't
  read this property in the bash code, so just write policy
  to both locations.

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

diff --git a/recipes-openxt/openxt/openxt-measuredlaunch/ml-functions b/recipes-openxt/openxt/openxt-measuredlaunch/ml-functions
--- a/recipes-openxt/openxt/openxt-measuredlaunch/ml-functions
+++ b/recipes-openxt/openxt/openxt-measuredlaunch/ml-functions
@@ -339,7 +339,9 @@ generate_policy() {
     if [ "${tpm2}" -eq 0 ]; then
         hash_alg=$(get_preferred_alg)
         [ $? -ne 0 ] && echo "No valid algs available" && return 1
+        #Two possible nv index locations on tpm2.0 that tboot checks
         local tboot_idx='0x01200001'
+        local tboot_idx2='0x01c10131'
     else
         local tboot_idx='0x20000001'
     fi
@@ -358,6 +360,12 @@ generate_policy() {
     if [ "${tpm2}" -eq 0 ]; then
         tpm2_nvdefine -x $tboot_idx -s $polsize -a 0x40000001 -P "$password" -t 0x60006 2>&1 1>/dev/null && \
         tpm2_nvwrite -x $tboot_idx -f $policy -a 0x40000001 -P "$password" 2>&1 1>/dev/null
+        if [ $? -ne 0 ]; then
+            echo "failed to write tboot Verified Launch policy to TPM" >&2
+            return 2
+        fi
+        tpm2_nvdefine -x $tboot_idx2 -s $polsize -a 0x40000001 -P "$password" -t 0x60006 2>&1 1>/dev/null && \
+        tpm2_nvwrite -x $tboot_idx2 -f $policy -a 0x40000001 -P "$password" 2>&1 1>/dev/null
     else
         tpmnv_defindex -i $tboot_idx -s $polsize -pv 0x02 -p "$password" 2>&1 1>/dev/null && \
         lcp_writepol -i $tboot_idx -f $policy -p "$password" 2>&1 1>/dev/null
